config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
  ComplexCondition:
    active: true
    threshold: 4
  TooManyFunctions:
    active: true
    thresholdInFiles: 15

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
  WildcardImport:
    active: true
    excludeImports: ['kotlinx.android.synthetic.*', 'java.util.*']

naming:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: "_|ignore|expected"

empty-blocks:
  active: true

coroutines:
  active: true

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
